// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfwUlenCYlr8yI51WwfP7C6A27Nf7U-rE',
    appId: '1:1058761577249:web:34bbd047d6078993626460',
    messagingSenderId: '1058761577249',
    projectId: 'safewalk-e37ff',
    authDomain: 'safewalk-e37ff.firebaseapp.com',
    storageBucket: 'safewalk-e37ff.firebasestorage.app',
    measurementId: 'G-N54590HVF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO1jmZ0V7X9oVIomt4pJvWXBTdk9k67Bw',
    appId: '1:1058761577249:android:cb589a0b6eb801f7626460',
    messagingSenderId: '1058761577249',
    projectId: 'safewalk-e37ff',
    storageBucket: 'safewalk-e37ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhzkef_CppvATxdV9rVArE2q36hsOML4Y',
    appId: '1:1058761577249:ios:48b0811a0405451b626460',
    messagingSenderId: '1058761577249',
    projectId: 'safewalk-e37ff',
    storageBucket: 'safewalk-e37ff.firebasestorage.app',
    iosBundleId: 'com.example.safewalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhzkef_CppvATxdV9rVArE2q36hsOML4Y',
    appId: '1:1058761577249:ios:48b0811a0405451b626460',
    messagingSenderId: '1058761577249',
    projectId: 'safewalk-e37ff',
    storageBucket: 'safewalk-e37ff.firebasestorage.app',
    iosBundleId: 'com.example.safewalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfwUlenCYlr8yI51WwfP7C6A27Nf7U-rE',
    appId: '1:1058761577249:web:2d75558a8dab53df626460',
    messagingSenderId: '1058761577249',
    projectId: 'safewalk-e37ff',
    authDomain: 'safewalk-e37ff.firebaseapp.com',
    storageBucket: 'safewalk-e37ff.firebasestorage.app',
    measurementId: 'G-CJMNH6SS7H',
  );
}
